name: Create macOs universal2/aarch64-apple-darwin python release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'py-v*' # Push events to matching py-v*, i.e. py-v1.0, py-v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest" ]
        python-version: [ "3.7" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Setup universal2 targets for Rust
        run: |
          rustup target add aarch64-apple-darwin
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: maturin publish
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          maturin-version: 1.8.7
          command: publish
          args: --target aarch64-apple-darwin --no-sdist --skip-existing -o wheels -i python -u yankun

