name: Create Python release manylinux

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'py-v*' # Push events to matching py-v*, i.e. py-v1.0, py-v20.15.10
jobs:
  linux:
    name: PyPi (x86_64)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [ x86_64 ]
    steps:
      - uses: actions/checkout@v3
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin==1.8.7
      - name: Publish wheel
        shell: bash
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
        run: |
          export RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3'
          maturin publish \
          --no-sdist \
          --skip-existing \
          -o wheels \
          -i python \
          --username yankun
  linux-cross:
    name: PyPi (cross)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [ aarch64, armv7, ppc64le, ppc64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: publish cross
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
        with:
          rust-toolchain: stable
          manylinux: auto
          target: ${{ matrix.target }}
          command: publish
          args: --no-sdist --skip-existing -o wheels -i python -u yankun
