name: Create Python release manylinux

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'py-v*' # Push events to matching py-v*, i.e. py-v1.0, py-v20.15.10
jobs:
  linux:
    name: PyPi (x86_64)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [ x86_64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: publish
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
        with:
          rust-toolchain: stable
          target: ${{ matrix.target }}
          manylinux: auto
          command: publish
          args: --no-sdist --skip-existing -o wheels -i python -u yankun
  linux-cross:
    name: PyPi (cross)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [ aarch64, armv7, ppc64le, ppc64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: publish cross
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
        with:
          rust-toolchain: stable
          manylinux: auto
          target: ${{ matrix.target }}
          command: publish
          args: --no-sdist --skip-existing -o wheels -i python -u yankun
