name: Test Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CONDA_PREFIX: /usr/share/miniconda

jobs:
  test:
    name: Build and test Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          echo $CONDA
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build.requirements.txt
      - name: Maturin develop
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: develop
          args: --release
      - name: save bloom filter to file
        run: python py_tests/test_save_file.py
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: chmod +x millw
      - run: ./millw fastbloomjvm.test
